export const FETCH_TOP_ARTISTS_REQUEST = 'FETCH_TOP_ARTISTS_REQUEST';
export const FETCH_TOP_ARTISTS_FAILURE = 'FETCH_TOP_ARTISTS_FAILURE';
export const FETCH_TOP_ARTISTS_SUCCESS = 'FETCH_TOP_ARTISTS_SUCCESS';
export const FETCH_TOP_ALBUMS_REQUEST = 'FETCH_TOP_ALBUMS_REQUEST';
export const FETCH_TOP_ALBUMS_FAILURE = 'FETCH_TOP_ALBUMS_FAILURE';
export const FETCH_TOP_ALBUMS_SUCCESS = 'FETCH_TOP_ALBUMS_SUCCESS';
export const FETCH_TOP_TRACKS_REQUEST = 'FETCH_TOP_TRACKS_REQUEST';
export const FETCH_TOP_TRACKS_FAILURE = 'FETCH_TOP_TRACKS_FAILURE';
export const FETCH_TOP_TRACKS_SUCCESS = 'FETCH_TOP_TRACKS_SUCCESS';

export const SET_THEME = 'SET_THEME';